// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Musicratic.Core.Data;

#nullable disable

namespace Musicratic.Core.Migrations
{
    [DbContext(typeof(MusicraticDbContext))]
    partial class MusicraticDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Musicratic.Core.Data.HubBannedTrackEntity", b =>
                {
                    b.Property<string>("HubId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackId")
                        .HasColumnType("TEXT");

                    b.HasKey("HubId", "TrackId");

                    b.ToTable("HubBannedTracks");
                });

            modelBuilder.Entity("Musicratic.Core.Data.HubEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("FadeOutDurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaybackState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayingTrackId")
                        .HasColumnType("TEXT");

                    b.Property<double>("PlayingTrackPositionSeconds")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Hubs");
                });

            modelBuilder.Entity("Musicratic.Core.Data.HubUserEntity", b =>
                {
                    b.Property<string>("HubId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("HubId", "UserId");

                    b.ToTable("HubUsers");
                });

            modelBuilder.Entity("Musicratic.Core.Data.TrackEntity", b =>
                {
                    b.Property<string>("HubId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.HasKey("HubId", "Id");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("Musicratic.Core.Data.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Musicratic.Core.Data.HubBannedTrackEntity", b =>
                {
                    b.HasOne("Musicratic.Core.Data.HubEntity", null)
                        .WithMany("BannedTracks")
                        .HasForeignKey("HubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Musicratic.Core.Data.HubUserEntity", b =>
                {
                    b.HasOne("Musicratic.Core.Data.HubEntity", null)
                        .WithMany("AttachedUsers")
                        .HasForeignKey("HubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Musicratic.Core.Data.TrackEntity", b =>
                {
                    b.HasOne("Musicratic.Core.Data.HubEntity", null)
                        .WithMany("Tracks")
                        .HasForeignKey("HubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Musicratic.Core.Data.HubEntity", b =>
                {
                    b.Navigation("AttachedUsers");

                    b.Navigation("BannedTracks");

                    b.Navigation("Tracks");
                });
#pragma warning restore 612, 618
        }
    }
}
