sonar.projectKey=musicratic
sonar.projectName=Musicratic
sonar.projectVersion=1.0

# Sources
sonar.sources=src,web/src,mobile/lib
sonar.tests=tests,web/src
sonar.test.inclusions=**/*.spec.ts,**/*Tests*.cs,**/*_test.dart

# Coverage reports
sonar.cs.opencover.reportsPaths=tests/**/coverage.opencover.xml
sonar.typescript.lcov.reportPaths=web/coverage/lcov.info

# Exclusions
sonar.exclusions=**/bin/**,**/obj/**,**/node_modules/**,.dart_tool/**
sonar.coverage.exclusions=**/Migrations/**,**/DependencyInjection.cs,**/Program.cs
